### ISSUE TITLE
如何将清理后的数据保存在osm

### ISSUE THREAD

**Issue by Geokeke** [yajiez/osm-data-wrangling#1]

**Comment by Geokeke** [comment]
你好，请问你是如何将经过 aduit.py 处理后的数据保存到 osm 文件中的？我看到你将整理结果打印出来，但好像并没有重新保存到 osm 中，导致输出成csv是没有经过清理的内容。

**Comment by yajiez** [comment]
数据清洗的过程是在 data.py 的 `shape_element` 函数中定义的，这个项目并没有对所有的数据问题进行清洗，只是挑选了一些问题作为示例，具体的可以阅读 PDF 报告中的相关内容
